// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// UserProfile contains the user personal information
type UserProfile struct {
	// Id is the user id which uniquely identify a user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Email is the unique email of the user
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// FirstName is the user first name,it does not have any min length as it can
	// be empty too.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// LastName is the user last Name , it does not have any min length as it can
	// be empty too.
	LastName string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// BirthDate is the user`s date of birth
	BirthDate *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	// Telephones are the user`s contact numbers and it should be saved with
	// country code.
	Telephones           []string `protobuf:"bytes,7,rep,name=telephones,proto3" json:"telephones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_3b96c1668c5b7ca0, []int{0}
}
func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (dst *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(dst, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserProfile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserProfile) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *UserProfile) GetTelephones() []string {
	if m != nil {
		return m.Telephones
	}
	return nil
}

type CreateUserProfileRequest struct {
	UserProfile          *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateUserProfileRequest) Reset()         { *m = CreateUserProfileRequest{} }
func (m *CreateUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserProfileRequest) ProtoMessage()    {}
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_3b96c1668c5b7ca0, []int{1}
}
func (m *CreateUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserProfileRequest.Unmarshal(m, b)
}
func (m *CreateUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserProfileRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserProfileRequest.Merge(dst, src)
}
func (m *CreateUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserProfileRequest.Size(m)
}
func (m *CreateUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserProfileRequest proto.InternalMessageInfo

func (m *CreateUserProfileRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetUserProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserProfileRequest) Reset()         { *m = GetUserProfileRequest{} }
func (m *GetUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserProfileRequest) ProtoMessage()    {}
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_3b96c1668c5b7ca0, []int{2}
}
func (m *GetUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserProfileRequest.Unmarshal(m, b)
}
func (m *GetUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserProfileRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserProfileRequest.Merge(dst, src)
}
func (m *GetUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserProfileRequest.Size(m)
}
func (m *GetUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserProfileRequest proto.InternalMessageInfo

func (m *GetUserProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserProfileRequest) Reset()         { *m = DeleteUserProfileRequest{} }
func (m *DeleteUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserProfileRequest) ProtoMessage()    {}
func (*DeleteUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_3b96c1668c5b7ca0, []int{3}
}
func (m *DeleteUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserProfileRequest.Unmarshal(m, b)
}
func (m *DeleteUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserProfileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserProfileRequest.Merge(dst, src)
}
func (m *DeleteUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserProfileRequest.Size(m)
}
func (m *DeleteUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserProfileRequest proto.InternalMessageInfo

func (m *DeleteUserProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateUserProfileRequest struct {
	UserProfile          *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateUserProfileRequest) Reset()         { *m = UpdateUserProfileRequest{} }
func (m *UpdateUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileRequest) ProtoMessage()    {}
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_3b96c1668c5b7ca0, []int{4}
}
func (m *UpdateUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileRequest.Unmarshal(m, b)
}
func (m *UpdateUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileRequest.Merge(dst, src)
}
func (m *UpdateUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileRequest.Size(m)
}
func (m *UpdateUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileRequest proto.InternalMessageInfo

func (m *UpdateUserProfileRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type ListUsersProfilesRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersProfilesRequest) Reset()         { *m = ListUsersProfilesRequest{} }
func (m *ListUsersProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersProfilesRequest) ProtoMessage()    {}
func (*ListUsersProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_3b96c1668c5b7ca0, []int{5}
}
func (m *ListUsersProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersProfilesRequest.Unmarshal(m, b)
}
func (m *ListUsersProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersProfilesRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersProfilesRequest.Merge(dst, src)
}
func (m *ListUsersProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersProfilesRequest.Size(m)
}
func (m *ListUsersProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersProfilesRequest proto.InternalMessageInfo

func (m *ListUsersProfilesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListUsersProfilesResponse struct {
	Profiles             []*UserProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUsersProfilesResponse) Reset()         { *m = ListUsersProfilesResponse{} }
func (m *ListUsersProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersProfilesResponse) ProtoMessage()    {}
func (*ListUsersProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_3b96c1668c5b7ca0, []int{6}
}
func (m *ListUsersProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersProfilesResponse.Unmarshal(m, b)
}
func (m *ListUsersProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersProfilesResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersProfilesResponse.Merge(dst, src)
}
func (m *ListUsersProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersProfilesResponse.Size(m)
}
func (m *ListUsersProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersProfilesResponse proto.InternalMessageInfo

func (m *ListUsersProfilesResponse) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*UserProfile)(nil), "appointy.user.v1.UserProfile")
	proto.RegisterType((*CreateUserProfileRequest)(nil), "appointy.user.v1.CreateUserProfileRequest")
	proto.RegisterType((*GetUserProfileRequest)(nil), "appointy.user.v1.GetUserProfileRequest")
	proto.RegisterType((*DeleteUserProfileRequest)(nil), "appointy.user.v1.DeleteUserProfileRequest")
	proto.RegisterType((*UpdateUserProfileRequest)(nil), "appointy.user.v1.UpdateUserProfileRequest")
	proto.RegisterType((*ListUsersProfilesRequest)(nil), "appointy.user.v1.ListUsersProfilesRequest")
	proto.RegisterType((*ListUsersProfilesResponse)(nil), "appointy.user.v1.ListUsersProfilesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserProfilesClient is the client API for UserProfiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserProfilesClient interface {
	// CreateProfile creates new user profile.
	CreateUserProfile(ctx context.Context, in *CreateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	// GetUserProfile returns the user profile by its unique user id.
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	// // DeleteUserProfile will delete the user profile from the system.
	DeleteUserProfile(ctx context.Context, in *DeleteUserProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	ListUsersProfiles(ctx context.Context, in *ListUsersProfilesRequest, opts ...grpc.CallOption) (*ListUsersProfilesResponse, error)
}

type userProfilesClient struct {
	cc *grpc.ClientConn
}

func NewUserProfilesClient(cc *grpc.ClientConn) UserProfilesClient {
	return &userProfilesClient{cc}
}

func (c *userProfilesClient) CreateUserProfile(ctx context.Context, in *CreateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/appointy.user.v1.UserProfiles/CreateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/appointy.user.v1.UserProfiles/GetUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) DeleteUserProfile(ctx context.Context, in *DeleteUserProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/appointy.user.v1.UserProfiles/DeleteUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/appointy.user.v1.UserProfiles/UpdateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) ListUsersProfiles(ctx context.Context, in *ListUsersProfilesRequest, opts ...grpc.CallOption) (*ListUsersProfilesResponse, error) {
	out := new(ListUsersProfilesResponse)
	err := c.cc.Invoke(ctx, "/appointy.user.v1.UserProfiles/ListUsersProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfilesServer is the server API for UserProfiles service.
type UserProfilesServer interface {
	// CreateProfile creates new user profile.
	CreateUserProfile(context.Context, *CreateUserProfileRequest) (*UserProfile, error)
	// GetUserProfile returns the user profile by its unique user id.
	GetUserProfile(context.Context, *GetUserProfileRequest) (*UserProfile, error)
	// // DeleteUserProfile will delete the user profile from the system.
	DeleteUserProfile(context.Context, *DeleteUserProfileRequest) (*empty.Empty, error)
	UpdateUserProfile(context.Context, *UpdateUserProfileRequest) (*UserProfile, error)
	ListUsersProfiles(context.Context, *ListUsersProfilesRequest) (*ListUsersProfilesResponse, error)
}

func RegisterUserProfilesServer(s *grpc.Server, srv UserProfilesServer) {
	s.RegisterService(&_UserProfiles_serviceDesc, srv)
}

func _UserProfiles_CreateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).CreateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointy.user.v1.UserProfiles/CreateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).CreateUserProfile(ctx, req.(*CreateUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointy.user.v1.UserProfiles/GetUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_DeleteUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).DeleteUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointy.user.v1.UserProfiles/DeleteUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).DeleteUserProfile(ctx, req.(*DeleteUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointy.user.v1.UserProfiles/UpdateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).UpdateUserProfile(ctx, req.(*UpdateUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_ListUsersProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).ListUsersProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointy.user.v1.UserProfiles/ListUsersProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).ListUsersProfiles(ctx, req.(*ListUsersProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserProfiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appointy.user.v1.UserProfiles",
	HandlerType: (*UserProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserProfile",
			Handler:    _UserProfiles_CreateUserProfile_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _UserProfiles_GetUserProfile_Handler,
		},
		{
			MethodName: "DeleteUserProfile",
			Handler:    _UserProfiles_DeleteUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _UserProfiles_UpdateUserProfile_Handler,
		},
		{
			MethodName: "ListUsersProfiles",
			Handler:    _UserProfiles_ListUsersProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_users_3b96c1668c5b7ca0) }

var fileDescriptor_users_3b96c1668c5b7ca0 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xdd, 0x36, 0xbb, 0xba, 0xb9, 0x59, 0x16, 0x3b, 0xa8, 0x8c, 0x59, 0x56, 0x97, 0xbc, 0xac,
	0xac, 0x30, 0xd5, 0xfa, 0xe4, 0x9b, 0x68, 0xc5, 0x17, 0x11, 0x29, 0x56, 0xb0, 0x08, 0x35, 0xa1,
	0xd3, 0x76, 0x20, 0xc9, 0x8c, 0x99, 0xa9, 0xd0, 0xbf, 0xe8, 0x3f, 0xf2, 0xcd, 0x9b, 0x49, 0x22,
	0x31, 0x1f, 0xd6, 0x17, 0xdf, 0x32, 0xe7, 0xdc, 0x7b, 0xe6, 0xcc, 0x3d, 0x37, 0xe0, 0xed, 0x34,
	0xcf, 0x34, 0x53, 0x99, 0x34, 0x92, 0xdc, 0x09, 0x95, 0x92, 0x22, 0x35, 0x7b, 0x96, 0xa3, 0xec,
	0xfb, 0x33, 0xff, 0x62, 0x23, 0xe5, 0x26, 0xe6, 0x63, 0xcb, 0x47, 0xbb, 0xf5, 0x98, 0x27, 0x0a,
	0x69, 0x7b, 0xf4, 0x1f, 0x35, 0x49, 0x23, 0x12, 0xae, 0x4d, 0x98, 0xa8, 0xa2, 0x20, 0xf8, 0x31,
	0x00, 0x6f, 0x8e, 0x4a, 0x1f, 0x32, 0xb9, 0x16, 0x31, 0x27, 0xe7, 0x30, 0x14, 0x2b, 0x3a, 0xb8,
	0x1a, 0x3c, 0x76, 0x67, 0xf8, 0x45, 0xee, 0xc2, 0x09, 0x4f, 0x42, 0x11, 0xd3, 0xa1, 0x85, 0x8a,
	0x03, 0xb9, 0x04, 0x58, 0x8b, 0x4c, 0x9b, 0x65, 0x1a, 0x26, 0x9c, 0x3a, 0x96, 0x72, 0x2d, 0xf2,
	0x1e, 0x01, 0x72, 0x01, 0x6e, 0x1c, 0x56, 0xec, 0xb1, 0x65, 0x4f, 0x73, 0xc0, 0x92, 0x2f, 0x00,
	0x22, 0x91, 0x99, 0xed, 0x72, 0x15, 0x1a, 0x4e, 0x4f, 0x90, 0xf5, 0x26, 0x3e, 0x2b, 0x7c, 0xb2,
	0xca, 0x27, 0xfb, 0x58, 0xf9, 0x9c, 0xb9, 0xb6, 0x7a, 0x8a, 0xc5, 0xe4, 0x21, 0x80, 0xe1, 0x31,
	0x57, 0x5b, 0x99, 0x72, 0x4d, 0x6f, 0x5f, 0x39, 0x28, 0x5c, 0x43, 0x82, 0x2f, 0x40, 0x5f, 0x67,
	0x1c, 0x2b, 0x6b, 0x2f, 0x9a, 0xf1, 0x6f, 0x3b, 0x54, 0x22, 0x2f, 0xe1, 0x2c, 0x9f, 0xd8, 0x52,
	0x15, 0xb0, 0x7d, 0xa2, 0x37, 0xb9, 0x64, 0xcd, 0x79, 0xb2, 0x7a, 0xaf, 0x1d, 0x7d, 0x79, 0x08,
	0xae, 0xe1, 0xde, 0x5b, 0x6e, 0x3a, 0xa4, 0x1b, 0x33, 0x0b, 0x6e, 0x80, 0x4e, 0xd1, 0x54, 0xa7,
	0x8d, 0x66, 0x2d, 0x5a, 0x9e, 0xab, 0xd5, 0xff, 0xb2, 0xfc, 0x14, 0xe8, 0x3b, 0xa1, 0xad, 0x67,
	0x5d, 0x62, 0xba, 0x52, 0xc7, 0x64, 0xf1, 0x23, 0xdb, 0x97, 0x66, 0x8a, 0x43, 0xf0, 0x09, 0x1e,
	0x74, 0x74, 0x68, 0x25, 0x53, 0x9d, 0x47, 0x77, 0x5a, 0x7a, 0xd1, 0xd8, 0xe5, 0x1c, 0x36, 0xf3,
	0xbb, 0x7c, 0xf2, 0xd3, 0x81, 0xb3, 0x1a, 0xa3, 0xc9, 0x57, 0x18, 0xb5, 0xb2, 0x22, 0x37, 0x6d,
	0xb9, 0xbe, 0x40, 0xfd, 0xbf, 0x5f, 0x1d, 0x1c, 0x91, 0x05, 0x9c, 0xff, 0x99, 0x17, 0xb9, 0x6e,
	0xb7, 0x74, 0x26, 0x7a, 0x58, 0xfb, 0x33, 0x8c, 0x5a, 0x11, 0x77, 0xb9, 0xef, 0xdb, 0x03, 0xff,
	0x7e, 0x6b, 0xe3, 0xdf, 0xe4, 0xbf, 0x2d, 0x4a, 0xe3, 0x60, 0x5a, 0x1b, 0xd1, 0x25, 0xdd, 0xb7,
	0x36, 0x87, 0xcd, 0xa7, 0x30, 0x6a, 0x65, 0xdc, 0x75, 0x43, 0xdf, 0xea, 0xf8, 0x4f, 0xfe, 0xa9,
	0xb6, 0x58, 0x9a, 0xe0, 0xe8, 0xd5, 0xf1, 0x62, 0xa8, 0xa2, 0xe8, 0x96, 0x7d, 0xe9, 0xf3, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xd2, 0x28, 0x58, 0xcf, 0x04, 0x00, 0x00,
}
